/**
 * 반 이름 자동 생성 유틸리티
 * 학년 + 과목 + 수준 + 구분자로 반 이름 생성
 */
import { ClassLevel } from '../api/classes';

// 수준별 라벨
const LEVEL_LABELS: Record<ClassLevel, string> = {
  advanced: '심화',
  regular: '정규1',
  regular2: '정규2',
  basic: '기초',
};

export interface GenerateClassNameParams {
  gradeName: string | null;    // "고1", "중2" 등
  subjectName: string | null;  // "수학", "영어" 등
  level: ClassLevel;
  suffix?: string;             // "A", "오후" 등 (선택)
}

/**
 * 반 이름 자동 생성
 * @example
 * generateClassName({ gradeName: '고1', subjectName: '수학', level: 'basic' })
 * // => "고1 수학 기초반"
 *
 * generateClassName({ gradeName: '고1', subjectName: '수학', level: 'basic', suffix: 'A' })
 * // => "고1 수학 기초반 A"
 *
 * generateClassName({ gradeName: '중2', subjectName: '영어', level: 'regular' })
 * // => "중2 영어반" (정규는 생략)
 */
export function generateClassName(params: GenerateClassNameParams): string {
  const { gradeName, subjectName, level, suffix } = params;

  if (!gradeName || !subjectName) return '';

  const levelLabel = LEVEL_LABELS[level];
  const levelPart = levelLabel ? ` ${levelLabel}` : '';
  const suffixPart = suffix?.trim() ? ` ${suffix.trim()}` : '';

  return `${gradeName} ${subjectName}${levelPart}반${suffixPart}`;
}

/**
 * 기존 반 이름에서 suffix 추출
 * @example
 * extractSuffixFromName("고1 수학 기초반 A", "고1", "수학", "basic")
 * // => "A"
 *
 * extractSuffixFromName("고1 수학 기초반", "고1", "수학", "basic")
 * // => ""
 */
export function extractSuffixFromName(
  fullName: string,
  gradeName: string | null,
  subjectName: string | null,
  level: ClassLevel
): string {
  if (!gradeName || !subjectName) return '';

  const baseName = generateClassName({ gradeName, subjectName, level });

  if (fullName.startsWith(baseName)) {
    return fullName.slice(baseName.length).trim();
  }

  // 패턴 매칭 실패 시 빈 문자열 반환
  return '';
}

/**
 * 반 이름이 자동 생성 패턴과 일치하는지 확인
 */
export function isAutoGeneratedName(
  fullName: string,
  gradeName: string | null,
  subjectName: string | null,
  level: ClassLevel
): boolean {
  if (!gradeName || !subjectName) return false;

  const baseName = generateClassName({ gradeName, subjectName, level });
  return fullName.startsWith(baseName);
}
